CREATE TABLE flats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    flat_number VARCHAR(100) NOT NULL,
    building_id BIGINT UNSIGNED NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    UNIQUE KEY uq_building_flat (building_id, flat_number)
);
